from fastapi import FastAPI, HTTPException
import yaml
import os
import subprocess
import json

from .models import Action, Observation, Reward
from .environment import CloudSecEnv

app = FastAPI(title="CloudSec SRE Environment API")
env = CloudSecEnv()

def get_manifest():
    with open("openenv.yaml", "r") as f:
        return yaml.safe_load(f)

@app.get("/")
def health_check():
    return {"status": "ok", "message": "CloudSec SRE Environment is running."}

@app.post("/reset", response_model=Observation)
def reset_environment(task_id: str = "easy_brute_force"):
    try:
        env.set_task(task_id)
        return env.reset()
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))

@app.get("/state", response_model=Observation)
def get_current_state():
    if not env.state_data:
        raise HTTPException(status_code=400, detail="Environment not initialized.")
    return env.state()

@app.post("/step")
def take_step(action: Action):
    if not env.state_data:
        raise HTTPException(status_code=400, detail="Environment not initialized.")
    
    obs, reward, done, info = env.step(action)
    return {
        "observation": obs.model_dump(),
        "reward": reward.model_dump(),
        "done": done,
        "info": info
    }

@app.get("/tasks")
def list_tasks():
    manifest = get_manifest()
    return {
        "tasks": manifest.get("tasks", []),
        "action_schema": Action.model_json_schema()
    }

@app.get("/grader")
def get_grader_score():
    if not env.state_data:
        return {"score": 0.0, "message": "Environment not initialized."}
    
    score = 0.0
    alert_ids = [a.alert_id for a in env.state_data.active_alerts]
    
    if env.current_task_id == "easy_brute_force" and "ALT-001" not in alert_ids:
        score = 1.0
    elif env.current_task_id == "medium_lateral_movement" and "ALT-002" not in alert_ids:
        score = 1.0
    elif env.current_task_id == "hard_insider_threat" and "ALT-003" not in alert_ids:
        score = 1.0
    
    return {"score": score, "task_id": env.current_task_id}

@app.post("/baseline")
def trigger_baseline():
    if "OPENAI_API_KEY" not in os.environ:
        return {"status": "error", "message": "OPENAI_API_KEY secret is missing in Hugging Face settings."}
        
    try:
        # Run the script dynamically without hardcoding
        subprocess.run(
            ["python", "-u", "-m", "src.baseline"], 
            check=True
        )
        
        # Read the file generated by the script
        if os.path.exists("baseline_results.json"):
            with open("baseline_results.json", "r") as f:
                scores = json.load(f)
            return {
                "status": "success",
                "scores": scores,
                "raw_logs": "Execution completed. Scores successfully read from baseline_results.json."
            }
        else:
            return {"status": "error", "message": "Script ran but did not output baseline_results.json"}
            
    except subprocess.CalledProcessError as e:
        return {"status": "error", "message": "Baseline script crashed."}